
spring:
  profiles:
    active: local
    group:
      local: local,common,secret
      blue: blue,common,secret
      green: green,common,secret

server:
  env: blue

---

spring:
  config:
    activate:
      on-profile: local

server:
  port: 8081
  serverAddress: localhost

serverName: local_server

---

spring:
  config:
    activate:
      on-profile: blue

server:
  port: 8081
  serverAddress: 52.78.180.103

serverName: blue_server

---

spring:
  config:
    activate:
      on-profile: green

server:
  port: 8082
  serverAddress: 52.78.180.103

serverName: green_server

---

spring:
  config:
    activate:
      on-profile: common

server:
  common: common